### PR TITLE
Gui.Event rewrite.

### PR DESCRIPTION
**Pull request by credomane**
Allows for creating per "element" events for on_click, on_state_changed, on_text_changed

Now that I'm making the pull request should the Gui.Event be split from stdlib/gui/gui.lua into a file of it's own? stdlib/gui/event.lua for example?

### CODE REVIEW

**Comment by credomane** [comment]
Oh I haven't written any tests for this...or updated the existing ones. So there is that still.

**Comment by Afforess** [comment]
You can almost certainly borrow heavily from the Event tests. It probably is failing at the moment due to you replacing the old GUI class, but not updating the gui_spec tests to reflect that.

**Comment by credomane** [comment]
>Failure → spec/gui/gui_spec.lua @ 32
Event .on_click should cascade through registered handlers
spec/gui/gui_spec.lua:41: Function was not called with the arguments

oh....Yeah. I broke that, apparently. The old on_click remembered all handlers but mine only keeps the most recent. Fix that in my code or update the test? Then make note of that possible breaking change in the future release notes?

**Comment by Afforess** [comment]
Update the tests. Nothing in the GUI class was in a release yet, so you can break the API freely. Only released APIs have to remain backwords compatible.

I only plan on releasing breaking major versions in lock-step with Factorio, but If possible, I'd like to avoid it altogether. I am rather proud that stdlib remains fully compatible with 0.12 and 0.13 simultaneously.

**Comment by credomane** [comment]
> I am rather proud that stdlib remains fully compatible with 0.12 and 0.13 simultaneously.
Hm...If that is the case then I probably need to do some checking in Gui.Event.dispatch, Gui.on_checked_state_changed and Gui.on_text_changed then for the existence of defines.events.on_gui_checked_state_changed and defines.events.on_gui_text_changed.

If I really wanted too I could probably fake them both. on_checked_state with a simple on_click hack. on_text_changed is trickier as i would have to listen to on_tick and compare the value store somewhere from the previous tick with the new tick before calling Gui.Event.dispatch().

**Comment by credomane** [comment]
Potential on_checked_state_changed faked event for stdlib in 0.12
https://gist.github.com/credomane/0a91c180f87911b4e03c24dedd083a0e

Still working on how to perform the text_changed. Thinking a Gui.Event.compat.v12={} to hold the textfield elements and their previous values then on_tick compare them for changes. firing a fake event like the gist does for the other when the text does change.

The problem I have with both is when the events are deregistered my fake event wrappers hang around. :(

**Comment by credomane** [comment]
I'm failing hard at these tests and I'm too tired to continue anymore tonight. So I gave up and pushed the tests in their current state. I feel as if I've spent more time on just getting a few tests working that I did for the whole reworked gui events. :/

**Comment by Afforess** [comment]
I didn't mean to mislead you on my 0.12 comment, you don't have to provide backwards support. I have no intentions of supporting it in newer releases.

**Comment by credomane** [comment]
> you don't have to provide backwards support

OK. Your last sentence got me to thinking I should try to backport the two new events. Not that I won't try to backport them anyways. Keep jotting down different ways as I get pissed at fixing the tests. It is keeping me sane, atm. :)

Btw. event_spec.lua is failing (even in master branch)

```
Error → spec/event/event_spec.lua @ 137
Event .dispatch should error when there are no connected players if a handler throws an error
spec/event/event_spec.lua:147: attempt to call method 'contains' (a nil value)
```

Also how do we get the defines.lua now that it is included in the exe? I need the two new on_gui_ events in the spec tests.

**Comment by Afforess** [comment]
>Btw. event_spec.lua is failing (even in master branch)

I'll take a look at that.

>Also how do we get the defines.lua now that it is included in the exe? I need the two new on_gui_ events in the spec tests.
 
You can always dump the contents into a file if you want the contents (on_init):

```
game.write_file('defines.lua', serpent.block(defines, {comment = false}))
```

And take a look at the script-output.

For testing, I have the defines from 0.12 in the spec/ directory. Feel free to update it with additional values added in 0.13. Then you can `require 'defines'` in your test specs.

**Comment by credomane** [comment]
OK. All of my tests are passing and I believe I have full test coverage too.

The CI will fail on some tests. namely the one I mentioned in event_spec.lua and the ones for `Gui.on_text_changed` and `on_checked_state_changed` because the defines.event.on_gui_* they depend on are not in the defines.lua. I'm not in a position to export the 0.13 ones out of Factorio to get the correct values. If you add their defines with any number they then pass.

**Comment by Afforess** [comment]
@credomane thanks for all the work on this. I have updated the defines.lua contents with the latest factorio 0.13 data, so all your tests pass!

**Comment by credomane** [comment]
Naturally, I found a bug in my code while doing some more playing around making sure the tests truly covered everything.

This one is kinda race condition-y. Have an element destroy() itself in it's own on_click handler. 
`Error: __CredoTesting__/stdlib/gui/gui.lua:49: LuaGuiElement API call when LuaGuiElement was invalid.`

Do I just commit the change to this branch for you to merge it into master or do I make a new one? I don't know git enough to risk attempting it. Gonna keep stressing my code. Should have seen the need recheck the valid state of the element after each handler.

Think what I will do is after the initial valid check before the loop I'll store the element name in a local variable for reuse in the loop. That way an extra if check on every loop iteration is prevented.

**Comment by Afforess** [comment]
You can reuse branches. Just make sure to git pull from the master of the
main repo to get the updated changes. Usually something like git pull
master <git url>

**Comment by credomane** [comment]
I'll try that in the future. I went ahead an made a new branch and PR for the fix earlier.

**Pull request merged**
